import { ArrowRight, ArrowUpRight, BatteryCharging, Camera, Instagram, MapPin, MessageCircle, PlugZap, Search, Smartphone, Wrench } from "lucide-react";
import Image from "next/image";
import { assetPath, GOOGLE_MAPS_URL, INSTAGRAM_URL, STORE_ADDRESS, TIKTOK_URL, WHATSAPP_URL } from "@/lib/constants";
import { WhatsAppButton } from "./ui";
import { HeroVisual } from "./hero-visual";
import { TikTokIcon } from "./social-icons";

const tickerText = "SMARTPHONES • REPARO • IPHONE • SAMSUNG • XIAOMI • MOTOROLA • ACESSÓRIOS • IGUATU •";

function TickerContent({ hidden = false }: { hidden?: boolean }) {
  return <div className="ticker-content" aria-hidden={hidden || undefined}>{Array.from({ length: 3 }, (_, index) => <span key={index}>{tickerText}</span>)}</div>;
}

export function Hero() {
  return <><section id="inicio" data-hero className="hero-section"><div className="container-page hero-layout"><div className="relative z-10 lg:-mr-10">
    <p className="hero-seq hero-seq-1 hero-kicker">SMARTPHONES <span>•</span> TODAS AS MARCAS <span>•</span> IGUATU</p>
    <h1 className="hero-seq hero-seq-2 hero-title"><span>Quebrou?</span><span>A gente</span><span className="text-brand">resolve.</span></h1>
    <p className="hero-seq hero-seq-3 mt-7 max-w-xl text-base leading-7 text-muted md:text-lg">Assistência técnica especializada para o seu smartphone. Reparos para iPhone, Samsung, Xiaomi, Motorola, Realme e outras marcas, com atendimento em Iguatu.</p>
    <div className="hero-seq hero-seq-4 mt-8 flex flex-col items-stretch gap-3 sm:flex-row sm:items-center"><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="brand-button group px-7"><MessageCircle className="brand-button-icon" size={18}/><span>Pedir orçamento</span><ArrowUpRight className="brand-button-arrow" size={17}/></a><a href="#servicos" className="editorial-link justify-center sm:justify-start">Ver todos os serviços <ArrowRight size={17}/></a></div>
    <p className="hero-seq hero-seq-5 mt-8 flex items-center gap-2 text-sm font-semibold text-slate-500"><MapPin size={17} className="shrink-0 text-brand"/> Iguatu, Ceará</p>
  </div><HeroVisual/></div></section><div className="ticker" aria-label={tickerText}><div className="ticker-track"><TickerContent/><TickerContent hidden/></div></div></>;
}

const iphoneServices = [
  [Smartphone, "Troca de tela", "Para tela quebrada, touch com problema ou falhas na imagem."],
  [BatteryCharging, "Troca de bateria", "Para aparelhos descarregando rápido ou com autonomia reduzida."],
  [PlugZap, "Conector de carga", "Diagnóstico e reparo quando o smartphone apresenta dificuldade para carregar."],
  [Search, "Diagnóstico", "Para problemas que ainda não foram identificados."],
  [Camera, "Câmeras e componentes", "Espaço para avaliar serviços relacionados a câmera e componentes."],
] as const;

export function IPhoneRepairs() {
  return <section id="reparos-iphone" className="section-pad bg-white"><div className="container-page"><div data-reveal className="iphone-intro"><div><p className="eyebrow">Reparos de smartphones</p><h2 className="section-heading mt-4">Seu smartphone em boas mãos.</h2></div><div className="max-w-xl"><p className="text-lg leading-8 text-muted">A Marcos Cell trabalha com diagnóstico e reparos em celulares de diferentes marcas, atendendo problemas comuns do dia a dia.</p><p className="mt-5 border-l-2 border-brand pl-4 text-sm font-bold leading-6 text-brand-dark">Assistência para smartphones em geral, com especialidade em iPhone.</p></div></div>
    <div className="iphone-services mt-12">{iphoneServices.map(([Icon, title, text], index) => <article key={title} data-reveal className="iphone-service"><span className="iphone-service-number">{String(index + 1).padStart(2, "0")}</span><Icon size={23} className="text-brand"/><h3>{title}</h3><p>{text}</p></article>)}</div>
    <div className="mt-9 flex flex-col items-start justify-between gap-5 border-t border-slate-200 pt-7 md:flex-row md:items-center"><p className="max-w-2xl text-sm leading-6 text-muted"><strong className="text-brand-dark">Experiência com smartphones.</strong> Atendimento para Samsung, Xiaomi, Motorola, Realme e outras marcas, além da especialidade em iPhones.</p><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="google-reviews-link min-h-11">Consultar reparo do meu celular <ArrowUpRight size={17}/></a></div>
  </div></section>;
}

const generalServices = [
  ["01", Smartphone, "Troca de tela", "Telas de iPhone e smartphones de diferentes marcas."],
  ["02", BatteryCharging, "Bateria", "Autonomia reduzida ou aparelho descarregando rápido."],
  ["03", PlugZap, "Conector de carga", "Dificuldade para carregar ou mau contato no conector."],
  ["04", Search, "Diagnóstico", "Avaliação para identificar a origem do problema."],
  ["05", Wrench, "Outras marcas", "Manutenção de Samsung, Xiaomi, Motorola, Realme e outros smartphones."],
] as const;

export function Services() {
  return <section id="servicos" className="section-pad bg-[#f5f8fc]"><div className="container-page"><p className="eyebrow">Assistência técnica</p><div data-reveal className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="section-heading max-w-3xl">Reparos profissionais<br/>para o seu smartphone.</h2><p className="max-w-sm pb-1 leading-7 text-muted">Atendimento para diversas marcas, com experiência especial em reparos de iPhone.</p></div><div className="general-services mt-12">{generalServices.map(([n, Icon, title, desc]) => <article key={n} data-reveal className="general-service"><span>{n}</span><Icon size={22}/><div><h3>{title}</h3><p>{desc}</p></div></article>)}</div></div></section>;
}

export function FeatureCta() { return <section id="contato" className="relative overflow-hidden bg-brand py-20 text-white md:py-28"><div className="hedgehog-shape absolute -bottom-36 right-[5%] h-[420px] w-[420px] bg-white opacity-[.055]"/><div className="speed-lines absolute right-0 top-16 h-5 w-80 text-white opacity-20"/><svg className="cta-lines absolute inset-0 h-full w-full opacity-20" preserveAspectRatio="none"><path d="M-100 280 Q350 40 900 180 T1600 40" fill="none" stroke="white" strokeWidth="2"/></svg><div data-reveal className="container-page relative"><h2 className="section-heading max-w-4xl text-white">Seu celular não precisa ficar parado.</h2><p className="mt-7 text-lg text-blue-100">Seja iPhone, Android ou aparelho de outra marca, conte o que aconteceu e peça um orçamento.</p><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="mt-9 inline-flex min-h-12 items-center gap-2 rounded-md bg-white px-7 py-3 font-black text-brand shadow-xl transition hover:-translate-y-1"><MessageCircle size={19}/> Falar no WhatsApp</a></div></section>; }

const productCards = [
  { label: "Capinhas", src: "/images/Produtos/capinha_telefone.png", alt: "Capinha para smartphone disponível na Marcos Cell" },
  { label: "Mag Power Volt", src: "/images/Produtos/carregador_portatil.png", alt: "Carregador portátil Mag Power da Volt" },
  { label: "PowerSync Volt", src: "/images/Produtos/powersync_produto.png", alt: "Carregador PowerSync da Volt" },
  { label: "Celulares", src: null, alt: "" },
  { label: "Acessórios", src: null, alt: "" },
] as const;

export function Products() { return <section id="produtos" className="section-pad bg-[#f5f8fc]"><div className="container-page"><div data-reveal className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Produtos</p><h2 className="section-heading mt-4">Também tem na<br/>Marcos Cell.</h2></div><p className="max-w-sm leading-7 text-muted">Capinhas, carregadores, smartphones e produtos Volt para o dia a dia.</p></div><div data-reveal className="products-grid mt-12"><div className="group relative col-span-2 row-span-2 overflow-hidden bg-white"><Image src={assetPath("/images/Produtos/cabos_foto.png")} alt="Cabo Flex Pro da Volt disponível na Marcos Cell" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-contain object-center transition duration-500 group-hover:scale-[1.015]"/><div className="absolute inset-x-0 bottom-0 h-28 bg-gradient-to-t from-black/65 to-transparent"/><p className="absolute bottom-5 left-5 text-xl font-black text-white md:bottom-7 md:left-7 md:text-2xl">Cabos Volt</p></div>{productCards.map((product,i) => <div key={product.label} className={`group relative overflow-hidden ${i===3 ? "col-span-2 bg-[#a8d1ff]" : "border border-slate-200 bg-white"}`}>{product.src ? <Image src={assetPath(product.src)} alt={product.alt} fill sizes="(max-width: 768px) 50vw, 25vw" className="object-contain object-center p-3 transition duration-500 group-hover:scale-[1.025]"/> : <div className="absolute right-[-20%] top-[15%] h-36 w-36 rounded-full border-[18px] border-brand/10 transition duration-500 group-hover:scale-105"/>}<p className="absolute bottom-3 left-3 bg-white/90 px-2 py-1 text-sm font-black text-brand-dark md:bottom-5 md:left-5 md:text-lg">{product.label}</p></div>)}</div><div className="mt-10 flex flex-col justify-between gap-5 border-t border-slate-300 pt-8 sm:flex-row sm:items-center"><p className="text-lg font-black">Acessórios e soluções Volt disponíveis na Marcos Cell.</p><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center gap-2 font-black text-brand">Consultar pelo WhatsApp <ArrowRight size={18}/></a></div></div></section>; }

export function AboutLocation() { return <><section id="sobre" className="section-pad bg-white"><div data-reveal className="container-page grid items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div className="store-photo group relative min-h-[360px] overflow-hidden bg-brand-dark md:min-h-[460px]"><Image src={assetPath("/images/Loja/fachada_loja.PNG")} alt="Fachada real da loja Marcos Cell em Iguatu" fill sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover object-center transition-transform duration-700 group-hover:scale-[1.015]"/><div className="absolute inset-0 bg-gradient-to-t from-brand-deep/35 via-transparent to-transparent"/><span className="photo-label">Nossa loja em Iguatu</span></div><div><p className="eyebrow">A loja</p><h2 className="section-heading mt-4">Experiência para cuidar do seu smartphone.</h2><p className="mt-7 max-w-lg text-lg leading-8 text-muted">Assistência técnica para iPhone, Samsung, Xiaomi, Motorola, Realme e outras marcas, com atendimento em Iguatu.</p><div className="mt-7 flex items-center gap-3 border-y border-slate-200 py-4"><Image src={assetPath("/images/Loja/consertando-telefone.webp")} alt="Técnico da Marcos Cell trabalhando na bancada" width={48} height={56} className="h-14 w-12 object-cover object-center"/><div><p className="text-sm font-black text-brand-dark">Atendimento técnico</p><p className="text-xs text-muted">Reparos de smartphones em geral</p></div></div><p className="mt-7 flex items-start gap-2 font-bold leading-6"><MapPin className="mt-0.5 shrink-0 text-brand" size={20}/><span>{STORE_ADDRESS}</span></p><a href="#localizacao" className="mt-7 inline-flex min-h-11 items-center gap-2 border-b-2 border-brand font-black text-brand-dark">Como chegar <ArrowRight size={18}/></a></div></div></section>
  <section id="localizacao" className="section-pad border-t border-slate-200 bg-[#f5f8fc]"><div data-reveal className="container-page location-layout"><div><p className="eyebrow">Localização</p><h2 className="section-heading mt-4">Passa na<br/>Marcos Cell.</h2><address className="mt-6 max-w-md not-italic text-lg leading-8 text-muted">{STORE_ADDRESS}</address><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><a href={GOOGLE_MAPS_URL} target="_blank" rel="noopener noreferrer" className="map-button">Abrir no Google Maps <ArrowUpRight size={17}/></a><WhatsAppButton>Chamar no WhatsApp</WhatsAppButton></div></div><a href={GOOGLE_MAPS_URL} target="_blank" rel="noopener noreferrer" aria-label="Abrir endereço da Marcos Cell no Google Maps" className="location-map"><div className="map-grid"/><div className="relative text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-brand text-white shadow-xl"><MapPin size={27}/></span><p className="mt-4 font-black">Alto do Juca, Iguatu</p><p className="mt-1 max-w-xs text-xs leading-5 text-muted">Av. Joaquim Ailton Alexandre, Nº 97</p></div></a></div></section></>; }

export function Footer() { return <><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" aria-label="Abrir WhatsApp" className="fixed bottom-5 right-5 z-40 grid h-14 w-14 place-items-center rounded-full bg-brand text-white shadow-2xl md:hidden"><MessageCircle/></a><footer className="bg-brand-deep py-14 text-white"><div className="container-page"><div className="footer-layout"><div><p className="text-4xl font-black tracking-[-.06em]">Marcos<span className="text-brand-electric">Cell</span><span className="text-brand">.</span></p><p className="mt-4 text-sm text-slate-400">Assistência técnica • Smartphones • iPhone • Acessórios</p><address className="mt-5 max-w-md not-italic text-sm leading-6 text-slate-400">Av. Joaquim Ailton Alexandre, Nº 97<br/>Alto do Juca • Iguatu — CE</address><div className="mt-5 flex items-center gap-4 text-slate-400"><span className="text-xs font-bold uppercase tracking-[.12em]">Siga a Marcos Cell</span><a href={INSTAGRAM_URL} target="_blank" rel="noopener noreferrer" aria-label="Instagram da Marcos Cell" className="footer-social-link"><Instagram size={20}/></a><a href={TIKTOK_URL} target="_blank" rel="noopener noreferrer" aria-label="TikTok da Marcos Cell" className="footer-social-link"><TikTokIcon width={20} height={20}/></a></div></div><nav className="footer-nav"><a href="#reparos-iphone">Reparos de smartphones</a><a href="#servicos">Serviços</a><a href={INSTAGRAM_URL} target="_blank" rel="noopener noreferrer">Instagram</a><a href={TIKTOK_URL} target="_blank" rel="noopener noreferrer">TikTok</a><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">WhatsApp</a><a href={GOOGLE_MAPS_URL} target="_blank" rel="noopener noreferrer">Google Maps</a></nav></div><div className="mt-12 flex flex-col justify-between gap-3 border-t border-white/10 pt-6 text-xs text-slate-500 sm:flex-row"><span>Iguatu, CE</span><span>© Marcos Cell. Todos os direitos reservados.</span></div></div></footer></>; }
